# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
target 'Demo1' do

pod 'Alamofire'
  target 'Demo1Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo1UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
